# Account

# ROLE_MANAGER cannot view any accounts
GET http://localhost:8080/accounts
Authorization: Basic manager_1 01_manager_01
###

# ROLE_USER can view their own accounts
GET http://localhost:8080/accounts
Authorization: Basic spiderman mrstark,Idontfeels0good
###

GET http://localhost:8080/accounts
Authorization: Basic iamironman i<3carmen
###

# ROLE_MANAGER can create new accounts
POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "customer_id": 3,
    "balance": 10000
}
###

POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "customer_id": 2,
    "balance": 1000000
}
###

POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "customer_id": 3,
    "balance": 50000,
    "available_balance": 50000
}
###

# PUT requests for accounts not supported
PUT http://localhost:8080/accounts/1
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "customer_id": 3,
    "balance": 20000,
    "available_balance": 5000
}
###

# DELETE requests for accounts not supported
DELETE http://localhost:8080/accounts/1
Authorization: Basic manager_1 01_manager_01
###

