# Account
GET http://localhost:8080/accounts
Authorization: Basic manager_1 01_manager_01
###

GET http://localhost:8080/customer/3/accounts
Authorization: Basic spiderman mrstark,Idontfeels0good
###

POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "customerId": 1,
    "balance": 100001,
    "availableBalance": 100001
}

###

POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "customerId": 3,
    "balance": 100000,
    "availableBalance": 100000
}

###

PUT http://localhost:8080/accounts/1
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "customerId": 1,
    "balance": 20000,
    "availableBalance": 5000
}

###

DELETE http://localhost:8080/accounts/3

###