# Content

GET http://localhost:8080/contents
Authorization: Basic manager_1 01_manager_01
###

GET http://localhost:8080/contents
Authorization: Basic analyst_1 01_analyst_01
###

GET http://localhost:8080/contents
Authorization: Basic iamironman i<3carmen
### 

GET http://localhost:8080/contents/1
Authorization: Basic iamironman i<3carmen
###

GET http://localhost:8080/contents/2
Authorization: Basic iamironman i<3carmen
### 

POST http://localhost:8080/contents
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title": "10 tips to save more money",
    "summary": "Handy tips to save money for the future",
    "content": "Lorem ipsum dolor sit amet",
    "link": "https://www.youtube.com/watch?v=oHg5SJYRHA0&feature=youtu.be",
    "approval": true
}
###

POST http://localhost:8080/contents
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "title": "KPMG Quarterly outlook Q2 2020",
    "summary": "Financial analysis of market performance in Q2 2020 by KPMG",
    "content": "KPMG reports on major accounting and financial reporting developments that could affect companies in the current period and near term.",
    "link": "https://frv.kpmg.us/reference-library/2020/q2-2020-quarterly-outlook.html",
    "approval": true
}
###

POST http://localhost:8080/contents
Content-Type: application/json
Authorization: Basic iamironman i<3carmen

{
    "title": "How to get rich QUICK",
    "summary": "Click the link for easy profit!!!",
    "content": "Just click the link!!",
    "link": "Don't have la",
    "approval": true
}
###

PUT http://localhost:8080/contents/3
Content-Type: application/json
Authorization: Basic analyst_2 02_analyst_02

{
    "title": "Rick roll",
    "summary": "Not good financial advice"
}
###

PUT http://localhost:8080/contents/3
Content-Type: application/json
Authorization: Basic iamironman i<3carmen

{
    "title": "How to get rich QUICK",
    "summary": "Click the link for easy profit!!!",
    "link" : "Don't have la"
}
###

DELETE http://localhost:8080/contents/3
Authorization: Basic iamironman i<3carmen
###

DELETE http://localhost:8080/contents/3
Authorization: Basic manager_1 01_manager_01
###

DELETE http://localhost:8080/contents/3
Authorization: Basic analyst_2 02_analyst_02
###