# Customer 
GET http://localhost:8080/api/customers
###

GET http://localhost:8080/api/customers
Authorization: Basic manager_1 01_manager_01
###

GET http://localhost:8080/api/customers/3
Authorization: Basic iamironman i<3carmen
###

GET http://localhost:8080/api/customers/3
Authorization: Basic spiderman mrstark,Idontfeels0good
###

POST http://localhost:8080/api/customers
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "full_name": "John Tan Xiao Ming",
    "nric": "S1937948E",
    "phone": "93410569",
    "address": "99 Bedok North Ave 4 #13-233 S460099",
    "username": "johntxm",
    "password": "johnpwsucks!1!",
    "authorities": "ROLE_USER",
    "active": true
}
###

POST http://localhost:8080/api/customers
Content-Type: application/json
Authorization: Basic iamironman i<3carmen

{
    "full_name": "Charlize Theron",
    "nric": "S1234567D",
    "phone": "90087654",
    "address": "Singapore Management University",
    "username": "theronlyone",
    "password": "donttryguessingthis",
    "authorities": "ROLE_USER",
    "active": true
}
###

# PUT request should only be able to modify phone, password and address
PUT http://localhost:8080/api/customers/2
Content-Type: application/json
Authorization: Basic iamironman i<3carmen

{
    "id": 2,
    "full_name": "Happy Stark",
    "nric": "S1234567D",
    "phone": "91908765",
    "address": "MCU Hall of fame",
    "username": "iamnotironman",
    "password": "i</3carmen",
    "authorities": "ROLE_USER",
    "active": false
}
###

# PUT request by manager should be able to change active as well
PUT http://localhost:8080/api/customers/2
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "phone": "91234567",
    "active": false
}
###

GET http://localhost:8080/api/portfolio
Content-Type: application/json
Authorization: Basic iamironman i<3carmen