# View portfolio
GET http://localhost:8080/portfolio
Authorization: Basic spiderman mrstark,Idontfeels0good
###

# Run this method after creating the new customer (John Tan) in Customer.http 
GET http://localhost:8080/portfolio
Authorization: Basic johntxm johnpwsucks!1!
###