GET http://localhost:8080/customers
Authorization: Basic admin goodpassword

###
GET http://localhost:8080/customers/1

###
DELETE http://localhost:8080/customers/4
Authorization: Basic admin goodpassword

###
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "name": "John Tan Xiao Ming",
    "nric": "S6834702H",
    "phoneNo": "93410569",
    "address": "99 Bedok North Ave 4 #13-233 S460099",
    "username": "johntxm",
    "password": "john1isbest!",
    "authorities": "MANAGER,USER",
    "status": "true"
}
###
POST http://localhost:8080/customers
Content-Type: application/json

{
    "id": "1",
    "name": "John Tan Xiao Ming",
    "nric": "S6834702H",
    "phoneNo": "93410569",
    "address": "99 Bedok North Ave 4 #13-233 S460099",
    "username": "johntxm",
    "password": "johnpwsucks!1!",
    "authorities": "USER",
    "status": "true"
}
###
PUT http://localhost:8080/customers/1
Content-Type: application/json
# Wrong username
Authorization: Basic dt goodpassword

{
    "username": "jphntxm"
}

###
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "username": "gooduser",
    "password": "goodpassword",
    "authorities": "USER"
}

DELETE http://localhost:8080/customers/4
Authorization: Basic admin goodpassword

