# Customer 

GET http://localhost:8080/customers

###
GET http://localhost:8080/customers/1

###
POST http://localhost:8080/customers
Content-Type: application/json

{
    "name": "Tony Stark",
    "nric": "S1234567A",
    "phoneNo": 91234567,
    "address": "Malibu",
    "username": "tstark",
    "password": "gooduser",
    "authorities": "ROLE_USER",
    "status": true
}

###

POST http://localhost:8080/customers
Content-Type: application/json

{
    "name": "John Cena",
    "nric": "S7654321B",
    "phoneNo": 98897007,
    "address": "WWE hall of fame",
    "username": "cantseeme",
    "password": "password",
    "authorities": "ROLE_USER",
    "status": true
}

###

PUT http://localhost:8080/customers/2
Content-Type: application/json

{
    "name": "Charlize Theron",
    "nric": "S2424567C",
    "phoneNo": 90087654,
    "address": "Singapore Management University",
    "username": "theronlyone",
    "password": "donttryguessingthis",
    "authorities": "ROLE_USER",
    "status": true
}
###

DELETE http://localhost:8080/customers/3

###

# Account
GET http://localhost:8080/accounts

###

GET http://localhost:8080/accounts/1

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "customerId": 1,
    "balance": 10000,
    "availableBalance": 5000
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "customerId": 2,
    "balance": 200,
    "availableBalance": 200
}

###

PUT http://localhost:8080/accounts/1
Content-Type: application/json

{
    "customerId": 1,
    "balance": 20000,
    "availableBalance": 5000
}

###

DELETE http://localhost:8080/accounts/3

###

# Transfer

GET http://localhost:8080/accounts/1/transfers

###

GET http://localhost:8080/accounts/1/transfers/1

###
POST http://localhost:8080/transfers
Content-Type: application/json

{
    "from": 1,
    "to": 2,
    "amount": 1000
}
