# View all stocks
GET http://localhost:8080/api/stocks
Authorization: Basic spiderman mrstark,Idontfeels0good
###

# View a single stock symbol
GET http://localhost:8080/api/stocks/A17U
Authorization: Basic spiderman mrstark,Idontfeels0good
###