# View all stocks
GET http://localhost:8080/stocks
Authorization: Basic spiderman mrstark,Idontfeels0good
###

# View a single stock symbol
GET http://localhost:8080/stocks/A17U
Authorization: Basic spiderman mrstark,Idontfeels0good
###

# View all trades
GET http://localhost:8080/trades
Authorization: Basic spiderman mrstark,Idontfeels0good
###

# View a single trade
GET http://localhost:8080/trades/1
Authorization: Basic spiderman mrstark,Idontfeels0good
###

# Make a trade
POST http://localhost:8080/trades
Content-Type: application/json
Authorization: Basic spiderman mrstark,Idontfeels0good

{
    "action": "buy",
    "symbol": "A17U",
    "quantity": 500,
    "bid": 3.00,
    "account_id": 1,
    "customer_id": 3
}
###

GET http://localhost:8080/portfolio
Authorization: Basic spiderman mrstark,Idontfeels0good
###

# Run this method after creating the new customer (John Tan) in Customer.http 
GET http://localhost:8080/portfolio
Authorization: Basic johntxm johnpwsucks!1!
###