# Transfer

# ROLE_USER can view their own transactions
GET http://localhost:8080/accounts/1/transactions
Authorization: Basic spiderman mrstark,Idontfeels0good
###

# ROLE_USER can create transactions between accounts
POST http://localhost:8080/accounts/1/transactions
Content-Type: application/json
Authorization: : Basic spiderman mrstark,Idontfeels0good

{
    "from": 1,
    "to": 2,
    "amount": 1000
}
###

# 'From' must match ID shown in URL
POST http://localhost:8080/accounts/1/transactions
Content-Type: application/json
Authorization: Basic spiderman mrstark,Idontfeels0good

{
    "from": 2,
    "to": 1,
    "amount": 1000
}
###

# Tony Stark sends Peter Parker 50,000 to help him fill his market buy trades
POST http://localhost:8080/accounts/2/transactions
Content-Type: application/json
Authorization: Basic iamironman i<3carmen

{
    "from": 2,
    "to": 1,
    "amount": 50000
}
###