# Transfer

GET http://localhost:8080/accounts/1/transfers

###

GET http://localhost:8080/accounts/1/transfers/1

###
POST http://localhost:8080/transfers
Content-Type: application/json

{
    "from": 1,
    "to": 2,
    "amount": 1000
}
